apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nitin.chauhan5@vodafone.com-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: nitin.chauhan5@vodafone.com.user.api.vbps.k8s.eu-central-1.aws.cps.vodafone.com
